//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SetDlg.rc
//
#define IDD_DLG_MAIN                    101
#define IDD_DIALOG1                     103
#define IDD_DIALOG2                     104
#define IDD_DIALOG3                     105
#define IDD_DIALOG4                     107
#define IDD_DIALOG5                     108
#define IDD_DIALOG6                     109
#define IDD_DIALOG7                     110
#define IDD_DIALOG8                     111
#define IDB_BITMAP1                     113
#define IDB_BITMAP2                     115
#define IDB_BITMAP3                     116
#define IDB_BMP_ABOUT                   116
#define IDC_BTN_VIDEO                   1001
#define IDC_BTN_AUDIO                   1002
#define IDC_BTN_VIDEO_TWO               1002
#define IDC_BTN_3D                      1003
#define IDC_BTN_ORDINARY                1004
#define IDC_BTN_SOUND                   1005
#define IDC_BTN_SUBTITLE                1006
#define IDC_BTN_BACK2DEFUALT            1009
#define IDC_ORD_STATIC_ONTOP2           1009
#define IDC_BTN_ABOUT                   1010
#define IDC_BTN_RELATIONSHIP            1011
#define IDC_BTN_APPLY                   1012
#define IDC_BTN_OK                      1013
#define IDC_BTN_CANCEL                  1014
#define IDC_VIDEO_STATIC_VIDEOLIST      1015
#define IDC_VIDEO_RADIO_ALWAY_EXPEND    1016
#define IDC_VIDEO_RADIO_AUTO_HIDE       1017
#define IDC_VIDEO_RADIO_OPEN_SAME       1018
#define IDC_VIDEO_RADIO_LOAD_FLODER     1019
#define IDC_VIDEO_STATIC_FULLMODE       1020
#define IDC_VIDEO_COM_FULLMODE          1021
#define IDC_VIDEO_STATIC_IMAGERATE      1022
#define IDC_VIDEO_COM_IMAGERATE         1023
#define IDC_VIDEO_CHECK_LOW_CPU         1024
#define IDC_VIDEO_CHECK_FULLSCREEN      1025
#define IDC_VIDEO_CHECK_WIN_2_VIDEO     1026
#define IDC_VIDEO_CHECK_VIDEO_2_WIN     1027
#define IDC_VIDEO_CHECK_LOAD_LAST_POS   1028
#define IDC_VIDEO_CHECK_HARD_SPEED      1029
#define IDC_VIDEO_CHECK_DEINTERLACE     1030
#define IDC_VIDEO_STATIC_LEFT_BRIGHTNESS 1031
#define IDC_VIDEO_STATIC_LEFT           1032
#define IDC_VIDEO_STATIC_RIGHT          1033
#define IDC_VIDEO_STATIC_LEFT_CONTRAST  1034
#define IDC_VIDEO_STATIC_LEFT_SATURATION 1035
#define IDC_VIDEO_STATIC_LEFT_HUE       1036
#define IDC_VIDEO_SLIDER_LEFT_BRIGHTNESS 1037
#define IDC_VIDEO_SLIDER_LEFT_CONTRAST  1038
#define IDC_VIDEO_SLIDER_LEFT_SATURATION 1039
#define IDC_VIDEO_SLIDER_LEFT_HUE       1040
#define IDC_VIDEO_STATIC_RIGHT_BRIGHTNESS 1041
#define IDC_VIDEO_STATIC_RIGHT_CONTRAST 1042
#define IDC_VIDEO_STATIC_RIGHT_SATURATION 1043
#define IDC_VIDEO_STATIC_RIGHT_HUE      1044
#define IDC_VIDEO_SLIDER_RIGHT_BRIGHTNESS 1045
#define IDC_VIDEO_SLIDER_RIGHT_CONTRAST 1046
#define IDC_VIDEO_SLIDER_RIGHT_SATURATION 1047
#define IDC_VIDEO_SLIDER_RIGHT_HUE      1048
#define IDC_VIDEO_BTN_PAGE_ONE3         1049
#define IDC_VIDEO_BTN_PAGE_TWO2         1050
#define IDC_VOICE_CHECK_AUTO_VOICE_DECODE 1051
#define IDC_VOICE_COM_MAX_VOICE         1052
#define IDC_VOICE_STATIC_CHANNEL        1053
#define IDC_SUBTITLE_CHECK_SHOWSUB      1054
#define IDC_SUBTITLE_GROUP_LATE         1055
#define IDC_EDIT1                       1056
#define IDC_SUBTITLE_EDIT_LATE_SHOW     1056
#define IDC_EDIT2                       1057
#define IDC_SUBTITLE_EDIT_LATE_SHOW_SIZE 1057
#define IDC_SUBTITLE_BTN_RESET          1058
#define IDC_SUBTITLE_COM_STYLE          1059
#define IDC_SUBTITLE_COM_SIZE           1060
#define IDC_SUBTITLE_STATIC_STYLE       1062
#define IDC_SUBTITLE_STATIC_SIZE        1063
#define IDC_SUBTITLE_STATIC_COLOR       1064
#define IDC_SUBTITLE_STATIC_LATE_SHOW   1065
#define IDC_SUBTITLE_STATIC_LATE_SHOW_SIZE 1066
#define IDC_SUBTITLE_STATIC_LATE_SHOW_MINI_SEC 1067
#define IDC_SUBTITLE_STATIC_LATE_SHOW_CODE 1068
#define IDC_RELA_GROUP_FILE_RELA        1069
#define IDC_RELA_CHECK_MP4              1070
#define IDC_RELA_CHECK_AVI              1071
#define IDC_RELA_CHECK_RMVB             1072
#define IDC_RELA_BTN_ALL_SELECT         1073
#define IDC_RELA_BTN_ALL_CANCEL         1074
#define IDC_PRTSCR_BTN_OPEN_PATH        1086
#define IDC_PRTSCR_COM_SAVE_CONT        1087
#define IDC_PRTSCR_COM_SAVE_FORMAT      1088
#define IDC_PRTSCR_STATIC_SAVE_PATH     1089
#define IDC_PRTSCR_STATIC_SAVE_FORMAT   1090
#define IDC_PRTSCR_EDIT_SAVE_PATH       1091
#define IDC_SUBTITLE_BTN_SELECT_COLOR   1093
#define IDC_CHECK1                      1094
#define IDC_VIDEO_CHECK_ONSHOW          1094
#define IDC_ABOUT_STATIC_PIC            1095
#define IDC_ORD_STATIC_LANGUAGE         1120
#define IDC_ORD_COM_LANGUAGE            1121
#define IDC_VIDEO_RADIO_SAME_CONTROL    1122
#define IDC_VIDEO_BTN_RESET             1123
#define IDC_VIDEO_GROUP_COLOR_CTROL     1124
#define IDC_VIDEO_GROUP_COLOR_CTROL_LEFT 1125
#define IDC_VIDEO_GROUP_COLOR_CTROL_RIGHT 1126
#define IDC_3D_CHECK_SHOW2D             1128
#define IDC_3D_CHECK_EXCHANGE           1130
#define IDC_3D_COM_INPUT_MODE           1131
#define IDC_3D_COM_OUTPUT_MODE          1132
#define IDC_3D_COM_FALL_MODE_ONE        1133
#define IDC_3D_SLIDER_INPUT_MODE        1135
#define IDC_3D_STATIC_INPUT_MODE        1136
#define IDC_3D_STATIC_OUTPUT_MODE       1137
#define IDC_3D_STATIC_FALL_MODE_ONE     1138
#define IDC_VOICE_COM_CHANNEL           1140
#define IDC_ORD_STATIC_ONTOP            1194
#define IDC_ORD_COM_TOPMOST             1195
#define IDC_ORD_RADIO_ONTRAY            1195
#define IDC_ORD_RADIO_CLOSE             1196
#define IDC_ORD_STATIC_CLOSE            1197
#define IDC_ORD_STATIC_BOOT             1198
#define IDC_ORD_RADIO_BOOT              1199
#define IDC_RELA_CHECK_3DV              1275
#define IDC_RELA_CHECK_TS               1276
#define IDC_RELA_CHECK_MKV              1277
#define IDC_RELA_CHECK_WMV              1278
#define IDC_RELA_CHECK_AV               1279
#define IDC_RELA_CHECK_VOB              1280
#define IDC_ABOUT_BACK                  1593

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
